### PR TITLE
Initial project setup

### LINKED ISSUE #2: Add storybook to provide samples

### PR DESCRIPTION
**Pull request by omiq17**
@screw123 
I have added the initial code structure. Successfully published the package to npm: https://www.npmjs.com/package/@bsol-oss/react-formik-generator
Tested the package by importing it to another project. It is running well.

But I am facing this below problem while creating the story (due to `schema-to-yup`):
error-01-03

Please check this issue.

### CODE REVIEW

**Comment by rosschiu** [comment]
Hi @omiq17 I saw this, do you think it's related?
https://github.com/kristianmandrup/schema-to-yup/issues/103
If yes we can change to webpack 5, not sure if it will help.

**Comment by omiq17** [comment]
> Hi @omiq17 I saw this, do you think it's related? [kristianmandrup/schema-to-yup#103](https://github.com/kristianmandrup/schema-to-yup/issues/103) If yes we can change to webpack 5, not sure if it will help.

Actually, we are not using `webpack` here, instead, we are using `rollup` as a package bundler. But while running the storybook,  we are getting an error for webpack loader which is kind of strange!
I have tried some ways, still could not solve this.

**Comment by rosschiu** [comment]
@omiq17 we are using rollup for our library no problem.  But storybook internally is using webpack.
when we type `yarn storybook`, it actually runs webpack, then launch a web server showing static content just like create react app.
So what I say is we upgrade storybook version see if it can helps.

**Comment by omiq17** [comment]
> @omiq17 we are using rollup for our library no problem. But storybook internally is using webpack. when we type `yarn storybook`, it actually runs webpack, then launch a web server showing static content just like create react app. So what I say is we upgrade storybook version see if it can helps.

Upgraded the storybook version. But the error remains!

**Comment by omiq17** [comment]
@screw123 
Found a way to test the library in CodeSandbox: https://codesandbox.io/s/react-fomik-generator-test-st5pi5?file=/src/App.js
Also updated the readme.

**Comment by kristianmandrup** [comment]
Hi @omiq17 I would like to help with this. Someone else from the community added the current bundling being used in my `schema-to-yup` library. Would love to convert it to typescript instead. Your thoughts?

**Comment by rosschiu** [comment]
> Hi @omiq17 I would like to help with this. Someone else from the community added the current bundling being used in my `schema-to-yup` library. Would love to convert it to typescript instead. Your thoughts?

Hi @kristianmandrup thanks for dropping by.
Do you mean you can update your library to solve the issue?

We can still survive but not able to use storybook is a bit annoying.

But if you mean you can help update `react-formik-generator` pls feel free!  We just started so it's ok and not much risk.

**Comment by kristianmandrup** [comment]
Yes, I meant updating my library to solve the issue. I'd also like to fix the array type handler once and for all. I never got around to that.

**Comment by rosschiu** [comment]
@kristianmandrup thanks!
then we will keep a close eye on schema-to-yup.  Once a new version is released we will try our code.

**Comment by kristianmandrup** [comment]
Should be fixed in latest push to master https://github.com/kristianmandrup/schema-to-yup/issues/103#issuecomment-1083112205

**Comment by omiq17** [comment]
> Should be fixed in latest push to master [kristianmandrup/schema-to-yup#103 (comment)](https://github.com/kristianmandrup/schema-to-yup/issues/103#issuecomment-1083112205)

@kristianmandrup Thanks a lot. The issue has been solved. I have successfully added the storybook.

**Pull request merged**
